// Code generated by go-swagger; DO NOT EDIT.

// Package restapi yaml2json
//
//  Converts incoming json, xml or properties to json, xml or properties.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
